name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check formatting
        run: |
          source venv/bin/activate
          black --check .

      - name: Linting
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run unit tests
        run: |
          source venv/bin/activate
          python -m unittest
